# If you find yourself editing this file very often, consider using Jekyll's
# data files feature for the data you need to update frequently.
#
# If you change this file, restart the server process 'bundle exec jekyll serve'

# Site settings (variables):
# In the HTML files, you can access them as {{ site.variable }}.

title: Luis Parra – Designer
email: luisparramail@gmail.com
description: >-
  Hi! I'm Luis Parra 😀. I'm a design student, and I'm ready to start my professional career.
baseurl: "/site"
url: "https://luisparradev.github.io"
twitter:
  username: luisparratweet
facebook:
  publisher: luisparramessage
  admins: luisparramessage
github_username:  luisparradev
logo: assets/images/profile-photo.jpg
social:
  name: Luis Parra
  links:
    - https://behance.net/luisparrawork
    - https://dribbble.com/luisparraworkshot
    - https://facebook.com/luisparramessage
    - https://flipboard.com/@luisparramag
    - https://github.com/luisparradev
    - https://highly.co/by/luisparrahighlight
    - https://instagram.com/luisparrapic/
    - https://issuu.com/luisparrapublication
    - https://linkedin.com/in/luisparrapro/
    - https://medium.com/@luisparrastory
    - https://pinterest.com/luisparraboard
    - https://luisparraworkspace.slack.com
    - https://twitter.com/luisparratweet

webmaster_verifications:
  google: # verified by HTML file and tag
lang: en_US

# Build settings
markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
plugins:
  - jekyll-feed
  - jemoji
  # SEO
  - jekyll-seo-tag
  - jekyll-sitemap
  # GitHub-Pages Defaults
  - jekyll-coffeescript
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-paginate
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-default-layout
  - jekyll-titles-from-headings

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

theme: jekyll-theme-minimal # Theme is neccesary for gh-pages, but I use CSS instead of a theme
